# Stage 1: Build the Go binary
FROM golang:1.23-alpine3.19 as go-build
WORKDIR /go/src/app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-w -s" -o /go/bin/example_client cmd/example/client.go

# Stage 2: Create the final image
FROM scratch
COPY --from=go-build /go/bin/example_client /go/bin/example_client
CMD [ "/go/bin/example_client" ]